DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS utterance;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);

CREATE TABLE utterance (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  response TEXT NOT NULL,
  author_id INTEGER NOT NULL,
  sync_ratio REAL NOT NULL,
  sentiment REAL NOT NULL,
  interactions INTEGER NOT NULL,
  source TEXT NOT NULL,
  model_name TEXT NOT NULL,
  FOREIGN KEY (author_id) REFERENCES user (id)
);